#!/bin/bash

if [ "$1" != "--finish" ]; then
    if [ -n "$CI_REGISTRY_USER" -a -n "$CI_REGISTRY_PASSWORD" -a -n "$CI_REGISTRY" ]; then
        echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    fi
fi
